management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://test.com
        allowed-methods: GET
  endpoint:
    health:
      show-components: ALWAYS
      show-details: always
    env:
      show-values: always
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  my-app:
    any-value: someValue
    group-id: "@project.groupId@"
    artifact-id: "@project.artifactId@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
  made-by: developerY